# Generated by Django 4.2.11 on 2024-08-30 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_seed_db"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="avg_rating",
        ),
    ]
