# Generated by Django 4.2.11 on 2024-08-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_remove_movie_avg_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="avg_rating",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
