# Generated by Django 4.2.11 on 2024-09-03 03:49

from django.db import migrations

# Generated by Django 4.2.11 on 2024-09-03 03:36

from django.db import migrations
# Generated by Django 4.2.11 on 2024-08-30 23:26
from django.db import migrations

def populate_db(apps, schema_editor):
    Movie = apps.get_model("movies", "Movie")
    Review = apps.get_model("movies", "Review")
    db_alias = schema_editor.connection.alias

    # Create movies
    Movie.objects.using(db_alias).bulk_create([
        Movie(title="Forrest Gump", runtime=142, release_date="1994-07-06"),
        Movie(title="Toy Story", runtime=77, release_date="1995-11-22"),
        Movie(title="Captain Phillips", runtime=134, release_date="2013-10-11"),
        Movie(title="Catch Me If You Can", runtime=141, release_date="2002-12-25"),
        Movie(title="Bridge of Spies", runtime=142, release_date="2015-10-16"),
        ])

    # Create reviews
    Review.objects.using(db_alias).bulk_create([
        Review(movie=Movie.objects.get(title="Forrest Gump"), name="Reviewer 1", rating=5),
        Review(movie=Movie.objects.get(title="Forrest Gump"), name="Reviewer 2", rating=4),
        Review(movie=Movie.objects.get(title="Toy Story"), name="Reviewer 1", rating=4),
        Review(movie=Movie.objects.get(title="Toy Story"), name="Reviewer 2", rating=5),
        Review(movie=Movie.objects.get(title="Captain Phillips"), name="Reviewer 1", rating=3),
        Review(movie=Movie.objects.get(title="Captain Phillips"), name="Reviewer 2", rating=4),
        Review(movie=Movie.objects.get(title="Catch Me If You Can"), name="Reviewer 1", rating=4),
        Review(movie=Movie.objects.get(title="Catch Me If You Can"), name="Reviewer 2", rating=5),
        Review(movie=Movie.objects.get(title="Bridge of Spies"), name="Reviewer 1", rating=4),
        Review(movie=Movie.objects.get(title="Bridge of Spies"), name="Reviewer 2", rating=3),
    ])


def empty_db(apps, schema_editor):
    Movie = apps.get_model("movies", "Movie")
    db_alias = schema_editor.connection.alias

    Movie.objects.using(db_alias).filter(title__in=[
        "Forrest Gump",
        "Toy Story",
        "Captain Phillips",
        "Catch Me If You Can",
        "Bridge of Spies",
    ]).delete()
class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_auto_20240903_0336"),
    ]

    operations = [
        migrations.RunPython(populate_db, empty_db),
    ]
